# Generated by Django 2.1.7 on 2019-03-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限标题')),
                ('url', models.CharField(max_length=64, verbose_name='权限范围')),
                ('action', models.CharField(default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': '10.权限',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限组')),
            ],
            options={
                'verbose_name_plural': '11.权限组',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '12.角色'},
        ),
        migrations.AlterModelOptions(
            name='userinfor',
            options={'verbose_name_plural': '13.用户信息'},
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.PermissionGroup'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='app01.Permission', verbose_name='拥有的所有权限'),
        ),
    ]
