# Generated by Django 2.1.7 on 2019-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190320_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseaccount',
            name='day_time',
            field=models.CharField(max_length=32, null=True, verbose_name='住房时间'),
        ),
    ]
