# Generated by Django 2.1.7 on 2019-03-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190320_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupleAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bath_house', models.IntegerField(default='', verbose_name='洗浴房间号')),
                ('set_meal', models.CharField(max_length=64, null=True, verbose_name='套餐')),
                ('start_time', models.CharField(default='', max_length=225, verbose_name='洗浴开始时间')),
                ('end_time', models.CharField(default='', max_length=225, verbose_name='洗浴结束时间')),
                ('price_bath_house', models.IntegerField(verbose_name='洗浴单间价格')),
            ],
            options={
                'verbose_name_plural': '14.洗浴单间',
            },
        ),
        migrations.CreateModel(
            name='stockAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(default='', max_length=64, verbose_name='进货名称')),
                ('goods_price', models.IntegerField(default='', verbose_name='进货价格')),
                ('goods_time', models.CharField(default='', max_length=64, verbose_name='进货时间')),
                ('goods_remark', models.CharField(max_length=255, null=True, verbose_name='进货备注')),
            ],
            options={
                'verbose_name_plural': '15.进货单',
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.PermissionGroup', verbose_name='权限所属组'),
        ),
    ]
