# Generated by Django 2.1.7 on 2019-03-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
